### ISSUE TITLE
Install Jabber server as part of Vagrant box

### ISSUE THREAD

**Issue by auxesis** [flapjack/vagrant-flapjack#2]
To provide a more complete user experience for people trying out Flapjack.

**Comment by Hobbsee** [comment]
I've attempted to get this up and running, with only limited success.

I actually don't think just installing a jabber server is too helpful for people, because people are still going to need to connect a jabber client separately to the server anyway.  People are more likely to hook this up to a test room in their existing jabber server (or hipchat, slack, whatever) - which they can easily do after modifying the config file.

The only other possibility here is that we include some web-based jabber client, and a server, but to me, that seems overkill.  If anyone actually wants that, and reports it, then I'm happy to revisit this one.

**Comment by jessereynolds** [comment]
Makes sense @Hobbsee
